# Generated by Django 3.1.5 on 2021-01-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='color',
            field=models.CharField(default=1, max_length=10, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
