# Generated by Django 3.1.5 on 2021-01-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('slogan', models.CharField(max_length=100, verbose_name='slogan')),
                ('instagram', models.CharField(max_length=255, verbose_name='instagram')),
                ('twitter', models.CharField(max_length=255, verbose_name='twitter')),
                ('linkedin', models.CharField(max_length=255, verbose_name='linkedin')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
