# Generated by Django 3.1.5 on 2021-01-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210116_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('svg', models.TextField(blank=True, verbose_name='SVG')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, verbose_name='twitter'),
        ),
    ]
