# Generated by Django 3.1.5 on 2021-01-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210117_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
