# Generated by Django 3.1.5 on 2021-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('slogan', models.CharField(blank=True, max_length=100, verbose_name='Slogan')),
                ('instagram', models.CharField(blank=True, max_length=255, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=255, verbose_name='Twitter')),
                ('linkedin', models.CharField(blank=True, max_length=255, verbose_name='Linkedin')),
                ('email', models.CharField(blank=True, max_length=150, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('phone2', models.CharField(blank=True, max_length=15, verbose_name='Phone 2')),
                ('maps', models.CharField(blank=True, max_length=15, verbose_name='Map')),
            ],
        ),
    ]
