# Generated by Django 3.1.5 on 2021-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company Name'),
        ),
    ]
